export enum Difficulty {
  EASY = 'Easy',
  MEDIUM = 'Medium',
  HARD = 'Hard'
}

export interface Question {
  id: string;
  topic: string;
  text: string;
  imageUrl?: string; // Base64 string for uploaded image
  aiAnswer?: string; // Answer generated by Gemini
  userNotes?: string;
  createdAt: number;
}

export interface Note {
  id: string;
  title: string;
  content: string; // Markdown content
  tags: string[];
  lastModified: number;
}

export interface QuizQuestion {
  question: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
}

export type ViewState = 'dashboard' | 'questions' | 'notes' | 'quiz';
